all: true                 # Whether or not to instrument all files (not just the ones touched by your test suite) 	Boolean 	false
check-coverage: false     # Check whether coverage is within thresholds, fail if not 	Boolean 	false
extension: # List of extensions that nyc should attempt to handle in addition to .js 	Array<String> 	['.js', '.cjs', '.mjs', '.ts', '.tsx', '.jsx']
  - ".js"
  - ".jsx"
  - ".cjs"
  - ".mjs"
  - ".ts"
  - ".tsx"
  - ".mts"
include: # See selecting files for coverage for more info 	Array<String> 	['**']
  - "**"
exclude: # See selecting files for coverage for more info 	Array<String> 	list
  - ".git/**"
  - ".idea/**"
  - ".nyc_output/**"
  - "coverage/**"
  - "node_modules/**"
  - "var/**"
  - "**/*.d.{ts,mts}"
  - "**/*.spec.{js,jsx,cjs,mjs,ts,tsx,mts}"
reporter: # May be set to a built-in coverage reporter or an npm package (dev)dependency 	Array<String> 	['text']
  - html
  - text
report-dir: coverage      # Where to put the coverage report files 	String 	./coverage
skip-full: false          # Don't show files with 100% statement, branch, and function coverage 	Boolean 	false
temp-dir: ".nyc_output"   # Directory to output raw coverage information to 	String 	./.nyc_output
